In [4]:
import numpy as np

a = np.random.randn(3,3)
b = np.random.randn(3,1)

c = a*b

print(a)
print(b)
print(c)


[[ 1.98021141  0.16990162  1.88932608]
 [ 0.50611944 -0.44460137  1.17203089]
 [ 0.3838748  -0.07418308  0.50190476]]
[[ 0.11032788]
 [ 1.28606195]
 [-1.0102524 ]]
[[ 0.21847252  0.01874489  0.20844534]
 [ 0.65090095 -0.5717849   1.50730433]
 [-0.38781044  0.07494364 -0.50705049]]
